[mqtt]
host = "localhost"
port = 1883
user = "user"
password = "password"
wildcard_topic = "sensor/+"

[sensor_triggers]
[sensor_triggers.home_armed]
sensors = ["door1", "window1"]
[sensor_triggers.armed]
sensors = ["door1", "window1", "motion1"]
[sensor_triggers.home_armed]
sensors = ["door1", "window1"]

[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
queue = "queue_name"

[alarmmanager]
host = "localhost"
port = 3000
