[sensor_triggers]
[sensor_triggers.home_armed]
sensors = ["door1", "window1"]
[sensor_triggers.armed]
sensors = ["door1", "window1", "motion1"]

[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
queue = "queue_name"

[alarmmanager]
host = "localhost"
port = 3000
